// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/micro.proto

package micro

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Micro service

func NewMicroEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Micro service

type MicroService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Micro_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Micro_PingPongService, error)
}

type microService struct {
	c    client.Client
	name string
}

func NewMicroService(name string, c client.Client) MicroService {
	return &microService{
		c:    c,
		name: name,
	}
}

func (c *microService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Micro.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Micro_StreamService, error) {
	req := c.c.NewRequest(c.name, "Micro.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microServiceStream{stream}, nil
}

type Micro_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type microServiceStream struct {
	stream client.Stream
}

func (x *microServiceStream) Close() error {
	return x.stream.Close()
}

func (x *microServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microService) PingPong(ctx context.Context, opts ...client.CallOption) (Micro_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Micro.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microServicePingPong{stream}, nil
}

type Micro_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type microServicePingPong struct {
	stream client.Stream
}

func (x *microServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *microServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *microServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *microServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Micro service

type MicroHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Micro_StreamStream) error
	PingPong(context.Context, Micro_PingPongStream) error
}

func RegisterMicroHandler(s server.Server, hdlr MicroHandler, opts ...server.HandlerOption) error {
	type micro interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Micro struct {
		micro
	}
	h := &microHandler{hdlr}
	return s.Handle(s.NewHandler(&Micro{h}, opts...))
}

type microHandler struct {
	MicroHandler
}

func (h *microHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.MicroHandler.Call(ctx, in, out)
}

func (h *microHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicroHandler.Stream(ctx, m, &microStreamStream{stream})
}

type Micro_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type microStreamStream struct {
	stream server.Stream
}

func (x *microStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *microHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.MicroHandler.PingPong(ctx, &microPingPongStream{stream})
}

type Micro_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type microPingPongStream struct {
	stream server.Stream
}

func (x *microPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *microPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *microPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
